config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  resources :high_scores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/high_score.rb
class HighScore < ApplicationRecord
  validates_presence_of :game, :score
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  before_action :set_high_score, only: [:show, :edit, :update, :destroy]

  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, notice: 'High score was successfully created.' }
        format.json { render :show, status: :created, location: @high_score }
      else
        format.html do
          flash.now[:notice] = 'Validation failed!'
          render :new
        end
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1
  # PATCH/PUT /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
        format.html { redirect_to @high_score, notice: 'High score was successfully updated.' }
        format.json { render :show, status: :ok, location: @high_score }
      else
        format.html { render :edit }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score.destroy
    respond_to do |format|
      format.html { redirect_to high_scores_url, notice: 'High score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_score_params
      params.require(:high_score).permit(:game, :score)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/high_scores/_form.html.erb
<%= form_with(model: high_score, local: true) do%>

  <%= react_component 'TextInput', name: 'high_score[game]', label: :game, error: high_score.errors[:game].join(',') %>
  <%= react_component 'TextInput', name: 'high_score[score]', type: :number, label: :score, error: high_score.errors[:score].join('.') %>

  <%= react_component 'SubmitInput', name: :submit, id: :submit %>
<% end %>

app/views/high_scores/edit.html.erb
<h1>Editing High Score</h1>

<%= render 'form', high_score: @high_score %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<%= react_component 'FlashMessage', text: flash[:notice] if flash[:notice] %>

<h1>High Scores</h1>

<%= react_component 'SimpleTable', data: @high_scores.to_json %>

<%= react_component 'FloatingAddButton', url: new_high_score_path %>

<!--# TODO: add to SimpleTable-->
<!--<td><%#= link_to 'Show', high_score %></td>-->
<!--<td><%#= link_to 'Edit', edit_high_score_path(high_score) %></td>-->
<!--<td><%#= link_to 'Destroy', high_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->

app/views/high_scores/new.html.erb
<h1>New High Score</h1>

<%= react_component 'FlashMessage', text: flash[:notice] if flash[:notice].present? %>

<%= render 'form', high_score: @high_score %>

<%= link_to 'Back', high_scores_path %>

app/views/high_scores/show.html.erb
<%= react_component 'FlashMessage', text: flash[:notice] if flash[:notice] %>

<p>
  <strong>Game:</strong>
  <%= @high_score.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @high_score.score %>
</p>

<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/home/index.html.erb
<%= react_component 'MaterialComponentList' %>
<h1>Home#index</h1>
<%= react_component 'GreetUser', name: 'marcos' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails6Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>